"""Add status field

Revision ID: a2990be71601
Revises: e229c051f483
Create Date: 2024-08-24 21:17:33.300917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2990be71601'
down_revision = 'e229c051f483'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = postgresql.ENUM('pending', 'success', 'failure', name='status_enum')
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('tests', sa.Column('status', status_enum, nullable=False, server_default='pending'))
    op.add_column('tests', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'message')
    op.drop_column('tests', 'status')

    # Remover o tipo ENUM
    status_enum = postgresql.ENUM('pending', 'success', 'failure', name='status_enum')
    status_enum.drop(op.get_bind(), checkfirst=True) 
    # ### end Alembic commands ###
