"""Add note field

Revision ID: dd71c05dfe6c
Revises: a2990be71601
Create Date: 2024-08-25 14:02:32.314053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd71c05dfe6c'
down_revision = 'a2990be71601'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('note', sa.String(), nullable=True))
    op.alter_column('tests', 'status',
               existing_type=postgresql.ENUM('pending', 'success', 'failure', name='status_enum'),
               nullable=True,
               existing_server_default=sa.text("'pending'::status_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'status',
               existing_type=postgresql.ENUM('pending', 'success', 'failure', name='status_enum'),
               nullable=False,
               existing_server_default=sa.text("'pending'::status_enum"))
    op.drop_column('tests', 'note')
    # ### end Alembic commands ###
