"""Add case name field

Revision ID: e8d4d4427ce8
Revises: dd71c05dfe6c
Create Date: 2024-08-25 14:32:34.847304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d4d4427ce8'
down_revision = 'dd71c05dfe6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('case_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'case_name')
    # ### end Alembic commands ###
